name: Publish Container

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  DOCKERFILE: ./distribution/docker/Dockerfile
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ghcr.io/ju6ge/paperless-field-extractor:latest-vulkan, ghcr.io/ju6ge/paperless-field-extractor:${{ env.RELEASE_VERSION }}-vulkan
          build-args: |
            INFERENCE_BACKEND=vulkan
          
